


spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}


# Disable Swagger
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
spring.jpa.open-in-view=false



# Disable SQL logging
spring.jpa.show-sql=false


# Production logging
logging.level.root=INFO