package com.backend.lcbapi.auth.enums;

public enum PermissionEnum {
    CREATE_PROFILE,
    READ_PROFILE,
    UPDATE_PROFILE,
    DELETE_PROFILE,
    CREATE_AVAILABILITY_WINDOW,
    VIEW_ALL_AVAILABILITY_WINDOW,
    VIEW_ALL_BOOKABLE_SLOTS,
    UPDATE_AVAILABILITY_WINDOW,
    DELETE_AVAILABILITY_WINDOW


}
