package com.backend.lcbapi.auth.enums;

public enum PermissionEnum {
    CREATE_PROFILE,
    READ_PROFILE,
    UPDATE_PROFILE,
    DELETE_PROFILE,
    CREATE_AVAILABILITY_WINDOW,
    VIEW_ALL_AVAILABILITY_WINDOW,
    VIEW_ALL_BOOKABLE_SLOTS,
    UPDATE_AVAILABILITY_WINDOW,
    DELETE_AVAILABILITY_WINDOW,
    CREATE_BOOKING,
    STUDENT_VIEW_BOOKING,
    LECTURER_VIEW_BOOKING,
    STUDENT_VIEW_ALL_BOOKINGS,
    LECTURER_VIEW_ALL_BOOKINGS,
    CANCEL_BOOKING_WITHOUT_REASON,
    STUDENT_CANCEL_BOOKING,
    CANCEL_SLOT,
    LECTURER_CANCEL_BOOKING


}
